fix build error
drivers/video/samsung/s3cfb_main.c:464:3: warning: too many arguments for format [-Wformat-extra-args]
   printk(KERN_DEBUG, "error on lcd33 regulator enable : lcd_regulator is null\n");